### ISSUE TITLE
Type of recursive expression not principal

### ISSUE THREAD

**Issue by AshleyYakeley** [LPTK/simple-sub#94]
I put this in the online demo:
```
let ignore = fun a -> fun b -> b
let rec f = fun x -> ignore (f 3) x
```

Results: `val f: 'a -> 'a ∨ int`.
Expected: `val f: 'a -> 'a`. I believe this is the principal type of the expression.

**Comment by LPTK** [comment]
Nope, MLsub/Simple-sub do not support polymorphic recursion, so this is the expected type. We type check recursive functions by treating all recursive occurrences at the same as the main definition, which starts as a fresh type variable in the implementation.

For the record, type inference for polymorphic recursion is undecidable.

**Comment by AshleyYakeley** [comment]
Oh huh, I did not know this.
